# Site settings
title: Make Weird Music
email: anthony@makeweirdmusic.com
description: > # this means to ignore newlines until "baseurl:"
  A resource for musicians to discover new artists, learn weird music techniques,
  listen to interviews, and share their weird music.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.makeweirdmusic.com" # the base hostname & protocol for your site
twitter_username: MakeWeirdMusic
github_username:  MakeWeirdMusic
s3_url: https://s3.amazonaws.com/audio.makeweirdmusic.com

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

sass:
  style: :compressed
  sass_dir: _sass

paginate: 6
paginate_path: "/page:num/"
