# Site settings
title: Make Weird Music
email: anthony@makeweirdmusic.com
description: Expanding the creative horizons of musicians and music enthusiasts. We feature interviews and educational content regarding the most creative musical artists in the world.
subtitle: Discover new artists, learn secret techniques, and share creative music.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.makeweirdmusic.com" # the base hostname & protocol for your site
twitter_username: MakeWeirdMusic
github_username:  MakeWeirdMusic
s3_url: http://s3.amazonaws.com/audio.makeweirdmusic.com
lang: en
author: Anthony Garone
copyright: "&#x2117; &amp; &#xA9; 2017"
repository: makeweirdmusic/makeweirdmusic.github.io
github: [metadata]

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

sass:
  style: :compressed
  sass_dir: _sass

paginate: 6
paginate_path: "/page:num/"
